### ISSUE TITLE
Help with systemd socket activation

### ISSUE THREAD

**Issue by christian-heusel** [robustirc/bridge#16]
Hey everyone! 🥳 
So I want to configure socket activation for the robustirc bridge and I am using the following configuration:
`robustirc.service`
```systemd
[Unit]
Description=RobustIRC bridge
Documentation=http://robustirc.net/

[Service]
Restart=on-failure
ExecStart=/home/chris/go/bin/robustirc-bridge -network=robustirc.net -socks=localhost:1080 -listen=

[Install]
WantedBy=default.target

````

`robustirc.socket`
```systemd
[Unit]
Description=robustirc-bridge
PartOf=robustirc.service

[Socket]
ListenStream=127.0.0.1:6667

[Install]
WantedBy=sockets.target
```
When I keep the configuration like above (as taken from the template unit files int the repo), the bridge is not activated when I start my IRC client and just gets a connection refused and if I change it to be `ListenStream=127.0.0.1:1080` it gets activated but the port is already in use.

To be fair my understanding of socket activation is rather small, but as far as I understood the two should be the same in order for the first request to activate the socket and pass it to the program. Any help / links to documentation is greatly appreciated ... 😊

**Comment by stapelberg** [comment]
With `-network=robustirc.net -socks=localhost:1080 -listen=`, you’re running in SOCKS-only mode: https://github.com/robustirc/bridge/blob/c2136b3251b00f865f1c3d4bb72d7f7c1f748528/robustirc-bridge/bridge.go#L540-L547

I think you need to set a non-empty network, but an empty -socks and empty -listen flag to hit the socket activation case: https://github.com/robustirc/bridge/blob/c2136b3251b00f865f1c3d4bb72d7f7c1f748528/robustirc-bridge/bridge.go#L572-L576

As you can tell, not many folks use socket activation apparently :)

We can definitely make the instructions/errors better for this case.

**Comment by christian-heusel** [comment]
So as it turns out you are ofc right regarding the configuration, but I spotted why I couldnt get it to work (the full configuration matrix was covered at one point ^^):
`$ go install github.com/robustirc/bridge/robustirc-bridge@latest` is giving me `v1.7` instead of `v1.8`

```
$ go version
go1.18.3 linux/amd64
$ go install github.com/robustirc/bridge/robustirc-bridge@latest
$ robustirc-bridge -version
RobustIRC Bridge v1.7
$ go install github.com/robustirc/bridge/robustirc-bridge@v1.8
go: github.com/robustirc/bridge/robustirc-bridge@v1.8: no matching versions for query "v1.8"
```
One can see [here](https://pkg.go.dev/github.com/robustirc/bridge/robustirc-bridge?tab=versions) that only a subset of the tags is listed.
I tried to fix that according to [the docs about module publishing (step 6)](https://go.dev/doc/modules/publishing), sadly without success:
```
$ GOPROXY=proxy.golang.org go list -m github.com/robustirc/bridge@v1.8
go: module github.com/robustirc/bridge: no matching versions for query "v1.8"
```

Initial problem is solved though by cloning and building from source, so feel free to close this as solved!
Thank you a lot for your help! 😃 👍🏻

**Comment by Merovius** [comment]
I believe the version must be tagged as `v.1.8.0`, i.e. it must be a full semantic version including patch version, to be recognized for module selection.

**Comment by stapelberg** [comment]
Thank you, @Merovius, that was it!

As soon as I pushed the v1.8.0 tag, it started working. The Go proxy now seems to resolve `github.com/robustirc/bridge@latest` to `github.com/robustirc/bridge v1.8.0` as expected :)

Edit: I pushed the wrong commit under the v1.8.0 tag, so I pushed v1.8.1 right afterwards.
