### ISSUE TITLE
 /LIST and /WHOIS

### ISSUE THREAD

**Issue by ravench** [robustirc/bridge#7]
It seems that there's no support yet for the standard  /LIST and /WHOIS commands.

`robustirc   -- | LIST: Unknown command`
`robustirc   -- | WHOIS: Unknown command`

(connected to the robustirc.net using weechat and the robustirc-bridge)

**Comment by stapelberg** [comment]
Indeed. If you're just looking for a channel, we are hanging out in #chaos-hd

**Comment by stapelberg** [comment]
This was fixed with https://github.com/robustirc/robustirc/issues/89 and https://github.com/robustirc/robustirc/issues/88 a while ago, but the repository wasn’t public back then :).
